[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/mariana.toml"]

[keyboard]
bindings = [
    # Ref tmux mapping to copy current pane
    { key = "A", mods = "Command", chars = "\u001b[24~" }
]

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

